### ISSUE TITLE
login/reg: Snackbar throws exception

### ISSUE THREAD

**Issue by ghpranav** [Argia-Org/incodnito#22] opened 2020-07-27 12:06 UTC
Calling snackbar to show message on login & registration page throws following error:

```
E/flutter (15045): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
E/flutter (15045): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is 
from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
```

**Comment by Baluds** [comment] 2020-07-27 18:44
The issue is fixed by providing it suitable context to locate scaffold widget

**Closed by Baluds** 2020-07-27 18:44 UTC
Labels: Priority: High, Status: In Progress, Type: Bug
